---
- name: Configure Prometheus + Grafana monitoring stack.
  hosts: rpi-node1
  gather_facts: false
  become: true

  environment:
    # The location of the kubeconfig file on the master.
    K8S_AUTH_KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    PATH: "~/go/bin:{{ ansible_env.PATH }}"

  tasks:
    - name: Add metallb chart repo.
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: "https://metallb.github.io/metallb"

    #- name: create namespace for metallb
    #  ansible.builtin.shell: kubectl create namespace metallb-system

    - name: Deploy metallb.
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        state: present
        values:
          alertmanager:
            enabled: false

    - name: Creating a config file for metallb ipaddresspool
      copy:
        dest: "/tmp/ipaddresspool.yaml"
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - 192.168.2.101-192.168.2.200

    - name: Creating a config file for metallb l2advertisement
      copy:
        dest: "/tmp/l2advertisement.yaml"
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: default
            namespace: metallb-system
          spec:
            ipAddressPools:
            - default-pool

    - name: apply ipaddresspool
      ansible.builtin.shell: kubectl apply -f /tmp/ipaddresspool.yaml

    - name: apply l2advertisement
      ansible.builtin.shell: kubectl apply -f /tmp/l2advertisement.yaml

    - name: Add longhorn chart repo.
      kubernetes.core.helm_repository:
        name: longhorn
        repo_url: "https://charts.longhorn.io"

    - name: create namespace for longhorn
      ansible.builtin.shell: kubectl create namespace longhorn-system

    - name: Deploy longhorn.
      kubernetes.core.helm:
        name: longhorn
        chart_ref: longhorn/longhorn
        release_namespace: longhorn-system
        state: present
        values:
          alertmanager:
            enabled: false

    - name: Add prometheus-community chart repo.
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Deploy Prometheus + Grafana Helm chart.
      kubernetes.core.helm:
        name: cluster-monitoring
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: default
        state: present
        values:
          alertmanager:
            enabled: false